### ISSUE TITLE
你好，请问可以分享下 FDDC2018金融算法挑战赛01－A股上市公司季度营收预测的代码吗

### ISSUE THREAD

**Issue by xuman-Amy** [geekinglcq/CDCS#1]
你好，最近在研究智能金融方面，想参考下天池大佬的代码和实现。
请问可以分享下 FDDC2018金融算法挑战赛01－A股上市公司季度营收预测的代码吗

**Comment by geekinglcq** [comment]
你好，前几名的代码似乎没有公开出来，找到两份其他代码，已经更新了。
