### ISSUE TITLE
我们也正在做一件类似的事情，或许可以合作一下？

### ISSUE THREAD

**Issue by zhpmatrix** [geekinglcq/CDCS#4]
只专注于自然语言处理的比赛：

https://github.com/zhpmatrix/nlp-competitions-list-review

和CDCS的区别主要有三个：

第一：专注于特定领域；

第二：对部分TOP方案进行的思路梳理；

第三：跟进最新的比赛；

**Comment by geekinglcq** [comment]
Hi，合作我觉得没有问题，但是我没有想到太好的合作方式，也许我们可以做一个互授权，允许在声明后从对方项目中摘取没有的解决方案？

**Comment by zhpmatrix** [comment]
@geekinglcq 

嗯，也行。我也是没想到比较好的合作方式。具体声明如何做，你来规范一下？

**Comment by geekinglcq** [comment]
我觉得可以在摘取的信息旁边标个emoji:🤝，然后在项目中说明该表情表示信息来自合作方及出处．

**Comment by iphysresearch** [comment]
欢迎合作推广 🤝 https://github.com/iphysresearch/DataSciComp

**Comment by zhpmatrix** [comment]
@iphysresearch 

DataSciComp也是一个非常棒的项目，现在需要一个更好的顶层架构把这些优秀的资源整合起来。
